### ISSUE TITLE
Pagination (Data Lost and Repeat)

### ISSUE THREAD

**Issue by AhmadMiladKakar** [nsia-infosys/data.gov.af#5]
When there are more datasets in the topic, data needs to paginate in several pages, after clicking on the next page, some data of the first page are repeating on the next page and some of them become lost.

**Comment by sediqamousavi** [comment]
@AhmadMiladKakar this problem resolved please check on data.gov.af:8090
our sort criteria (sort by changed) can't give our entries a unique position and then bug occurs
In our view interface, under "Sort Criteria" I added a filter called : "Indexed Node: Entity ID" and placed it third under the "Indexed Node: Date created (Exposed)" filter.

**Comment by sediqamousavi** [comment]
@AhmadMiladKakar I close this issue if you see this problem again please open issue
